server:
  host: 0.0.0.0
  port: 3000

log_level: info

badger_db:
  directory: /app/data

rpc:
  url: 127.0.0.1:8332
  user: btc
  password: btc2022

indexer:
  batch_size: 1000000
  block_chan_buf: 100
