server:
  host: 0.0.0.0
  port: 3000

log_level: info

db:
  dir: ./tmp
  db_type: goleveldb

rpc:
  url: btc_node:8332
  user: btc
  password: btc2022

indexer:
  batch_size: 100
  block_chan_buf: 100
